# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: apps/desktop/packaging/homebrew/ in orochibraru/penombre.
class PenombreSync < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.64"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync-canary", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "2089e690164341458a7856003504984f00feff382a4a7bb87eeece4a23f010f4"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "388be978a984319dcf49a20abddb918fcc70215786e286676fd2deb85de15d13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a8ade73569312f5403a67f9194c0914ada829aa4855f61967134f4d9b1882ffa"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
