# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: apps/desktop/packaging/homebrew/ in orochibraru/penombre.
class PenombreSyncCanary < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.65-canary.1"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "df05936d6039a1bad5199162711619e1d20f7844c2761d50750d3cf7af439457"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "9a2d08e26e81681b4face31aa01ea2f680fe07a9c2de871c16368ef0e9812141"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a3d3b000f069d93ce582c75be2adac27e7378e94aa02b7f34fc13e57b28973b6"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
