# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: packaging/homebrew/ in orochibraru/penombre.
class PenombreSyncCanary < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.59-canary.1"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "5d0f30ea57385d1fda3c9da10457a953523a35a2b80f3e3f3f9e8808cb9cfe92"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "4bbb1f5303f947813a885f57d424582ef00d08ca45e50de246f2dad6f48062da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ab28b2fde994af291d610d8d56ed6fbbf3d5efe61f0b1ce89fcaf55808ff6a38"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
