# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: packaging/homebrew/ in orochibraru/penombre.
class PenombreSync < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.61"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync-canary", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "7b394f8938dfd08e0e94ab0f3d69b691de240b47877519e6e34494134510eb4e"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "a2463b60cdc2e423b23fbfd525efc915421831157d6a36c0862efa5f52ece632"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7b2ee521a39f7df21a26e2fd59052352c45c19daaec45b9b68e83727a047b496"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
