# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: packaging/homebrew/ in orochibraru/penombre.
class PenombreSyncCanary < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.62-canary.1"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "7144778809765fff8f2656538b6261e5d7d8e574e63eabbe1fb5a25e2bd723f9"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "c776e00139e53268ac32c461eff31f84121436e8977ae0a6616856ac61b3d791"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8d0cfa4a75d4b950359a815bff934b6178ecc2007aa66a8575d3f17cd607940c"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
