# Generated by Penombre's publish workflow for every release; edits here are
# overwritten. Source: apps/desktop/packaging/homebrew/ in orochibraru/penombre.
class PenombreSync < Formula
  desc "Tray app keeping local folders in two-way sync with a Penombre server"
  homepage "https://orochibraru.com/penombre/docs/desktop"
  version "1.8.65"
  license "MIT"

  depends_on "rclone"

  conflicts_with "penombre-sync-canary", because: "both install a penombre-sync binary"

  on_macos do
    on_arm do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-aarch64-apple-darwin.tar.gz"
      sha256 "df3a669e50a19e3baa3c6cada7819a9a66a530a7de8ecba13d6a0da35255cd44"
    end
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-apple-darwin.tar.gz"
      sha256 "ba9319cbb1ed6c82c0ae3581520e0d54db99e98c6b7eda0e00e67949d7bcff73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orochibraru/penombre/releases/download/v#{version}/penombre-sync-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a1a4538abe429ae604ce36f89be45e9f26102989ad94e149dd127eb47308f16a"
    end
  end

  def install
    bin.install "penombre-sync"
  end

  # Quitting from the tray exits 0 and stays quit; only a crash restarts it.
  service do
    run opt_bin/"penombre-sync"
    run_type :immediate
    keep_alive crashed: true
    process_type :interactive
    environment_variables PATH: std_service_path_env
    log_path var/"log/penombre-sync.log"
    error_log_path var/"log/penombre-sync.log"
  end

  test do
    assert_predicate bin/"penombre-sync", :executable?
  end
end
